### ISSUE TITLE
Could not pass event BlockBreakEvent to PyroMining vv2.1.0 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by WhiteDragon0911** [MostWantedMinx/My-Plugins#11]
[18:18:20 ERROR]: Could not pass event BlockBreakEvent to PyroMining vv2.1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(Player
InteractManager.java:290) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f
6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:217) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4
cf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:889) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [
spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [
spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.
12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NumberFormatException: For input string: "[0/100]"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.
8.0_181]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_181]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_181]
        at me.arsmagica.Listeners.Pickaxe.PickaxeXPSystemListener.onMine(Pickaxe
XPSystemListener.java:155) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar:git-Spigot-642f6d2-57ab4cf]
        ... 17 more

I'm Use Spigot 1.12.2 !!

**Comment by MostWantedMinx** [comment]
Will look into this ASAP. Thanks for the report.

**Comment by MostWantedMinx** [comment]
Could you please send me your messages.yml file? Thanks!

**Comment by WhiteDragon0911** [comment]
[messages.zip](https://github.com/MostWantedMinx/My-Plugins/files/2385590/messages.zip)
Here

**Comment by MostWantedMinx** [comment]
Thank you.
