### ISSUE TITLE
NoSuchMethodError on player connect

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#7]
Spigot 1.13.1 latest
PWP 1.1.0

These were generated every second when I connected (in survival mode). They stopped when I changed to creative mode. I know, just warnings, but still... filling the console/log.
```
[17:41:51] [Server thread/WARN]: [PyroWeatherPro] Task #1322 for PyroWeatherPro v1.1.0 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
        at me.arsmagica.WeatherTypes.AcidRain$5.run(AcidRain.java:273) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:41:52] [Server thread/WARN]: [PyroWeatherPro] Task #1322 for PyroWeatherPro v1.1.0 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
        at me.arsmagica.WeatherTypes.AcidRain$5.run(AcidRain.java:273) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar-2018-09-09-1737:git-Spigot-145a37a-022b8c3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by SlimeDog** [comment]
Duplicate #5
